### ISSUE TITLE
本リポジトリがROS教育用サービスで利用されているようです

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/motoman_project#118]
嬉しいニュースです。

たまたま見つけたのですが、下記のROS教育サービスで、ここのmotomanがチュートリアルとして利用されているようです。

![nishidalab_motoman](http://www.theconstructsim.com/wp-content/uploads/2018/01/Screenshot-from-2017-08-24-222545-1024x521.png)

https://www.youtube.com/watch?v=_ULJrmJ7xOo&feature=youtu.be

コマンドラインやlaunchファイル名も確認しましたが、見覚えのあるモノばかり。先端もジャミングだし、間違いなく西田研のものを使っています。

完成度が認められているということで、誇っていいことだと思います ^^ 世界中の人が見ているかもしれませんね。

コレを糧に、もっと進化させたいですね！

このIssueは、少し様子を見た後に閉じます。以上、情報共有でした。

**Comment by TakeshiNishida** [comment]
ROSが5分で使えるという内容ですね！また、べた褒めですね。「素晴らしい！詳しくどうやってるかわかんないけど」というのにはすこし笑いました。

**Comment by Ry0** [comment]
無駄にリアルなロボット台も世界デビューできてうれしそうです。頑張ってアセンブリしてよかった！

**Comment by MoriKen254** [comment]
:smile:

**Comment by MoriKen254** [comment]
レスありがとうございました :laughing: 

閉じます。
