### ISSUE TITLE
MoveIt! について

### ISSUE THREAD

**Issue by RyodoTanaka** [Nishida-Lab/motoman_project#25]
@Ry0 
気づいたというか、なんと言うことはない話なのですが、MoveIt用のモデルを作る際に、Gripperをlink_tとtool_0に設定していました。なので、プランナーは６自由度のハンドのプランニングを行っていますよね？
今日の昼に実装していく時に、とりあえず、６自由度でいいやということで先に進み、最後の方に、このプランニング、６自由度になってないか？という議論があったような気がします。
よく考えたら当たり前でしたね。
そこで、提案なのですが、
1. Gripper要素をtool_0だけにする
2. tool_0のリンクの位置を、link_tの回転軸からずらした位置に設定する

とするのはいかがでしょうか？
link_tの回転軸上に置くのではなく、この前の安川電機の教習所のロボットのように、tool_0の位置をlink_tの回転軸から少しずらした位置に設定し直すということです。

こうすれば、MoveItのプランナーが７自由度に対応できているのかの検証にもなると思います。というか、対応していなかったら、この研究室で取り組むべき課題になると思います。この辺までやるとやっと私の卒業研究テーマに近づけるような気もします。。。

あ、あと、MoveItでプランニングしてるかっけぇ動画リンクをリポジトリトップのREADMEに貼りませんか？

また、東京から帰ったら取り組みましょう！
以上、よろしくお願いします。

**Comment by Ry0** [comment]
確かにそうなってますね
`kdl_kinematics_plugin/KDLKKinematicsPlugin`は6軸用のキネマティクスを解くプラグインだそうで自然な流れだと思う．
マウスでロボットの位置を指定できる場所はB軸ですが，指定する姿勢はB軸から末端までのリンクの姿勢です．

![6axis](https://cloud.githubusercontent.com/assets/8924325/11496567/23410674-9856-11e5-89d2-40a9b028ac93.png)

PR2もそんな感じになってる．PR2も7軸(肩がぐいんぐいんなるところから1つめ〜)
しかしPR2は赤いリングをマウスで回したらｍｏｔｏｍａｎのT軸に相当するところが動きます．
これが理想的な動きだと思います．

![screenshot from 2015-12-01 18 30 33](https://cloud.githubusercontent.com/assets/8924325/11497043/a79ef2d4-9859-11e5-83f2-2170fad8bfe4.png)

言ってたとおりツール座標系をT軸とずらせば，なんか起こりそうだけど，現状でもマウスでどんな位置姿勢をとらせてもT軸の関節角度が一定なので，モーションプランニングされてないように見えますが，初期角度と目標角度と一致しているからであって，RRTとかのアルゴリズム的には7軸すべてプランニングできるはず．

現状じゃ，T軸の目標角度を設定できてないのが良くない．

moveitアシスタントで定義したように完璧にグループによってプランニングが切り分けられているなら話は別だけど
現状じゃよくわかんない！
