### ISSUE TITLE
リポジトリのWikiについて

### ISSUE THREAD

**Issue by Ry0** [Nishida-Lab/motoman_project#45]
最近，リポジトリのWikiの更新がなされていません．  
インストール方法が書かれている方法と異なったり，launchするファイルが違うファイルのものに変わっていたりします．
このままでは誤解を招くだけなので，はやめに情報の更新を行うようにします．

**Comment by Ry0** [comment]
最近の更新を踏まえて，motomanを動かすためのコマンドとわかっていることを[ここ](https://github.com/Nishida-Lab/motoman_project/wiki/Motion-planning-for-Real-robot-and-Gazebo-simulation-robot-%5BJapanese%5D)にまとめました．
わかっていないことが多いので，理解しながらWikiも充実させていきます．

**Comment by RyodoTanaka** [comment]
@Ry0 
ありがとう！！！
