### ISSUE TITLE
疑問

### ISSUE THREAD

**Issue by nakaomasato** [Nishida-Lab/motoman_project#86]
Wikiの中のインストールという項目で最初にある
catkin_ws
というのがよくわかりません。
wsという部分だけ任意の名前にしてよいのでしょうか？
また、catkin_ws全てを任意の名前のディレクトリにしてもよいのでしょうか？

**Comment by RyodoTanaka** [comment]
@nakaomasato 
`catkin_ws`というのは`catkin workspace`の略称です．
`catkin_ws`自体，好きな名前にしてもらってOKです．

例として僕の場合は，`motoman_ws`としています．

**Comment by nakaomasato** [comment]
ありがとうございます
